version: '3.8'

services:
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    networks:
      - backendapi
    environment:
      SA_PASSWORD: "82384580vV!@#"
      ACCEPT_EULA: "Y"
    ports:
      - "1450:1433"

  mongo:
    image: mongo
    container_name: meu-monga
    networks:
      - backendapi
    environment:
      MONGO_INITDB_ROOT_USERNAME: "adm"
      MONGO_INITDB_ROOT_PASSWORD: "123"
    ports:
      - "27017:27017"

  webapiproduct:
    image: webapiproduct
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "47662:80"
    networks:
      - backendapi
    depends_on:
      - sqlserver
      - mongo

networks:
  backendapi:
    driver: bridge